"""add visit_number

Revision ID: 4bb49ac216ad
Revises: b58ee506553a
Create Date: 2024-08-28 22:52:08.713153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bb49ac216ad'
down_revision = 'b58ee506553a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('footjoint_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visit_number', sa.Integer(), nullable=False))

    with op.batch_alter_table('lab_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visit_number', sa.Integer(), nullable=False))

    with op.batch_alter_table('largejoint_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visit_number', sa.Integer(), nullable=False))

    with op.batch_alter_table('lefthand_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visit_number', sa.Integer(), nullable=False))

    with op.batch_alter_table('righthand_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visit_number', sa.Integer(), nullable=False))

    with op.batch_alter_table('score_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visit_number', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score_data', schema=None) as batch_op:
        batch_op.drop_column('visit_number')

    with op.batch_alter_table('righthand_data', schema=None) as batch_op:
        batch_op.drop_column('visit_number')

    with op.batch_alter_table('lefthand_data', schema=None) as batch_op:
        batch_op.drop_column('visit_number')

    with op.batch_alter_table('largejoint_data', schema=None) as batch_op:
        batch_op.drop_column('visit_number')

    with op.batch_alter_table('lab_data', schema=None) as batch_op:
        batch_op.drop_column('visit_number')

    with op.batch_alter_table('footjoint_data', schema=None) as batch_op:
        batch_op.drop_column('visit_number')

    # ### end Alembic commands ###
