"""empty message

Revision ID: 80f1f51b1f46
Revises: 
Create Date: 2024-08-25 00:25:35.119235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80f1f51b1f46'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('score_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('distal_joints', sa.Integer(), nullable=True),
    sa.Column('proximal_joints', sa.Integer(), nullable=True),
    sa.Column('immunology_score', sa.Integer(), nullable=False),
    sa.Column('inflammation_score', sa.Integer(), nullable=False),
    sa.Column('joint_score', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('duration_score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('footjoint_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pt_id', sa.String(length=50), nullable=False),
    sa.Column('mtp_joint_left_1', sa.Integer(), nullable=True),
    sa.Column('mtp_joint_left_2', sa.Integer(), nullable=True),
    sa.Column('mtp_joint_left_3', sa.Integer(), nullable=True),
    sa.Column('mtp_joint_left_4', sa.Integer(), nullable=True),
    sa.Column('mtp_joint_left_5', sa.Integer(), nullable=True),
    sa.Column('mtp_joint_right_1', sa.Integer(), nullable=True),
    sa.Column('mtp_joint_right_2', sa.Integer(), nullable=True),
    sa.Column('mtp_joint_right_3', sa.Integer(), nullable=True),
    sa.Column('mtp_joint_right_4', sa.Integer(), nullable=True),
    sa.Column('mtp_joint_right_5', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hand_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pt_id', sa.String(length=50), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('right_hand_path', sa.String(length=255), nullable=False),
    sa.Column('left_hand_path', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('right_hand_result', sa.Float(), nullable=True),
    sa.Column('left_hand_result', sa.Float(), nullable=True),
    sa.Column('result', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lab_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pt_id', sa.String(length=50), nullable=False),
    sa.Column('crp', sa.Float(), nullable=True),
    sa.Column('esr', sa.Integer(), nullable=True),
    sa.Column('rf', sa.Float(), nullable=True),
    sa.Column('acpa', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('largejoint_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pt_id', sa.String(length=50), nullable=False),
    sa.Column('wrist_joint_hand_left', sa.Integer(), nullable=True),
    sa.Column('wrist_joint_hand_right', sa.Integer(), nullable=True),
    sa.Column('elbow_joint_left', sa.Integer(), nullable=True),
    sa.Column('elbow_joint_right', sa.Integer(), nullable=True),
    sa.Column('shoulder_joint_left', sa.Integer(), nullable=True),
    sa.Column('shoulder_joint_right', sa.Integer(), nullable=True),
    sa.Column('hip_joint_left', sa.Integer(), nullable=True),
    sa.Column('hip_joint_right', sa.Integer(), nullable=True),
    sa.Column('knee_joint_left', sa.Integer(), nullable=True),
    sa.Column('knee_joint_right', sa.Integer(), nullable=True),
    sa.Column('ankle_joint_left', sa.Integer(), nullable=True),
    sa.Column('ankle_joint_right', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lefthand_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pt_id', sa.String(length=50), nullable=False),
    sa.Column('dip_joint_left_2', sa.Integer(), nullable=True),
    sa.Column('dip_joint_left_3', sa.Integer(), nullable=True),
    sa.Column('dip_joint_left_4', sa.Integer(), nullable=True),
    sa.Column('dip_joint_left_5', sa.Integer(), nullable=True),
    sa.Column('thumb_ip_joint_left', sa.Integer(), nullable=True),
    sa.Column('pip_joint_left_2', sa.Integer(), nullable=True),
    sa.Column('pip_joint_left_3', sa.Integer(), nullable=True),
    sa.Column('pip_joint_left_4', sa.Integer(), nullable=True),
    sa.Column('pip_joint_left_5', sa.Integer(), nullable=True),
    sa.Column('mp_joint_left_1', sa.Integer(), nullable=True),
    sa.Column('mp_joint_left_2', sa.Integer(), nullable=True),
    sa.Column('mp_joint_left_3', sa.Integer(), nullable=True),
    sa.Column('mp_joint_left_4', sa.Integer(), nullable=True),
    sa.Column('mp_joint_left_5', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('righthand_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pt_id', sa.String(length=50), nullable=False),
    sa.Column('dip_joint_right_2', sa.Integer(), nullable=True),
    sa.Column('dip_joint_right_3', sa.Integer(), nullable=True),
    sa.Column('dip_joint_right_4', sa.Integer(), nullable=True),
    sa.Column('dip_joint_right_5', sa.Integer(), nullable=True),
    sa.Column('thumb_ip_joint_right', sa.Integer(), nullable=True),
    sa.Column('pip_joint_right_2', sa.Integer(), nullable=True),
    sa.Column('pip_joint_right_3', sa.Integer(), nullable=True),
    sa.Column('pip_joint_right_4', sa.Integer(), nullable=True),
    sa.Column('pip_joint_right_5', sa.Integer(), nullable=True),
    sa.Column('mp_joint_right_1', sa.Integer(), nullable=True),
    sa.Column('mp_joint_right_2', sa.Integer(), nullable=True),
    sa.Column('mp_joint_right_3', sa.Integer(), nullable=True),
    sa.Column('mp_joint_right_4', sa.Integer(), nullable=True),
    sa.Column('mp_joint_right_5', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('symptom',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pt_id', sa.String(length=50), nullable=False),
    sa.Column('sex', sa.String(length=10), nullable=True),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('birth_month', sa.Integer(), nullable=True),
    sa.Column('birth_day', sa.Integer(), nullable=True),
    sa.Column('disease_duration', sa.Integer(), nullable=True),
    sa.Column('morning_stiffness', sa.String(length=50), nullable=True),
    sa.Column('stiffness_duration', sa.Integer(), nullable=True),
    sa.Column('pain_level', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('six_weeks_duration', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('symptom')
    op.drop_table('righthand_data')
    op.drop_table('lefthand_data')
    op.drop_table('largejoint_data')
    op.drop_table('lab_data')
    op.drop_table('hand_data')
    op.drop_table('footjoint_data')
    op.drop_table('user')
    op.drop_table('score_data')
    # ### end Alembic commands ###
