"""empty message

Revision ID: 859bd4e85092
Revises: f13a2fba59a8
Create Date: 2024-08-15 02:04:30.189237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '859bd4e85092'
down_revision = 'f13a2fba59a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('symptom', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('symptom', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
