"""add_other_proximal_joints

Revision ID: ac1a43761d2d
Revises: bc7e1d7c235c
Create Date: 2024-08-29 02:28:06.818733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac1a43761d2d'
down_revision = 'bc7e1d7c235c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('symptom', schema=None) as batch_op:
        batch_op.alter_column('six_weeks_duration',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=3),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('symptom', schema=None) as batch_op:
        batch_op.alter_column('six_weeks_duration',
               existing_type=sa.String(length=3),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###
