"""add visit_number

Revision ID: b58ee506553a
Revises: da71b1faa3a7
Create Date: 2024-08-28 22:46:04.834833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b58ee506553a'
down_revision = 'da71b1faa3a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('symptom', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visit_number', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('symptom', schema=None) as batch_op:
        batch_op.drop_column('visit_number')

    # ### end Alembic commands ###
