"""add visit_number

Revision ID: c69efe677aec
Revises: 4bb49ac216ad
Create Date: 2024-08-28 22:57:49.731656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c69efe677aec'
down_revision = '4bb49ac216ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hand_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visit_number', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hand_data', schema=None) as batch_op:
        batch_op.drop_column('visit_number')

    # ### end Alembic commands ###
