"""Added disease_duration to symptom

Revision ID: d74caeb70951
Revises: 84b46cd6da3f
Create Date: 2024-08-21 22:43:09.405500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd74caeb70951'
down_revision = '84b46cd6da3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('symptom', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disease_duration', sa.Integer(), nullable=True))
        batch_op.drop_column('onset_day')
        batch_op.drop_column('onset_month')
        batch_op.drop_column('onset_year')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('symptom', schema=None) as batch_op:
        batch_op.add_column(sa.Column('onset_year', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('onset_month', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('onset_day', sa.INTEGER(), nullable=True))
        batch_op.drop_column('disease_duration')

    # ### end Alembic commands ###
